import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <>{children}</>;
  // <html lang="fr">
  //   <body
  //     className={`${geistSans.variable} ${geistMono.variable} antialiased`}
  //   >
  //   </body>
  // </html>
}
